import { NextRequest, NextResponse } from 'next/server'

export const runtime = 'nodejs'
export const maxDuration = 60

interface FileEntry {
  path: string
  content: string
}

interface CommitPayload {
  productName: string
  productSlug: string
  description: string
  files: FileEntry[]
  githubUsername: string
  githubToken: string
}

export async function POST(req: NextRequest) {
  const { productName, productSlug, description, files, githubUsername, githubToken } =
    await req.json() as CommitPayload

  const headers = {
    'Authorization': `Bearer ${githubToken}`,
    'Accept': 'application/vnd.github+json',
    'Content-Type': 'application/json',
    'X-GitHub-Api-Version': '2022-11-28',
    'User-Agent': 'AgentCo-Platform/1.0',
  }

  const repoName = productSlug.toLowerCase().replace(/[^a-z0-9-]/g, '-')
  const baseUrl = `https://api.github.com/repos/${githubUsername}/${repoName}`

  // 1. Create or verify repo exists
  const createRes = await fetch('https://api.github.com/user/repos', {
    method: 'POST',
    headers,
    body: JSON.stringify({
      name: repoName,
      description,
      private: false,
      auto_init: false,
    }),
  })

  const createData = await createRes.json()

  // If already exists that's fine, otherwise check for real errors
  if (!createRes.ok && createData.errors?.[0]?.message !== 'name already exists on this account') {
    return NextResponse.json(
      { error: `Failed to create repo: ${createData.message}` },
      { status: 400 }
    )
  }

  // 2. Create blobs for each file
  const blobs: Array<{ path: string; mode: string; type: string; sha: string }> = []

  for (const file of files) {
    try {
      const blobRes = await fetch(`${baseUrl}/git/blobs`, {
        method: 'POST',
        headers,
        body: JSON.stringify({
          content: Buffer.from(file.content, 'utf-8').toString('base64'),
          encoding: 'base64',
        }),
      })

      if (!blobRes.ok) {
        const err = await blobRes.json()
        console.error(`Blob failed for ${file.path}:`, err.message)
        continue
      }

      const blob = await blobRes.json()
      blobs.push({ path: file.path, mode: '100644', type: 'blob', sha: blob.sha })
    } catch (e) {
      console.error(`Blob error for ${file.path}:`, e)
    }
  }

  if (blobs.length === 0) {
    return NextResponse.json({ error: 'No files could be uploaded as blobs' }, { status: 500 })
  }

  // 3. Create tree (no base_tree for initial commit on empty repo)
  const treeRes = await fetch(`${baseUrl}/git/trees`, {
    method: 'POST',
    headers,
    body: JSON.stringify({ tree: blobs }),
  })

  if (!treeRes.ok) {
    const err = await treeRes.json()
    return NextResponse.json({ error: `Tree creation failed: ${err.message}` }, { status: 500 })
  }

  const tree = await treeRes.json()

  // 4. Create commit (no parents for first commit)
  const commitRes = await fetch(`${baseUrl}/git/commits`, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      message: `feat: initial scaffold — ${productName}\n\nGenerated by AgentCo Platform\n7 AI agent divisions · Claude API`,
      tree: tree.sha,
      parents: [],
    }),
  })

  if (!commitRes.ok) {
    const err = await commitRes.json()
    return NextResponse.json({ error: `Commit creation failed: ${err.message}` }, { status: 500 })
  }

  const commit = await commitRes.json()

  // 5. Create main branch ref
  const refRes = await fetch(`${baseUrl}/git/refs`, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      ref: 'refs/heads/main',
      sha: commit.sha,
    }),
  })

  // If ref already exists, force update it
  if (!refRes.ok) {
    const patchRes = await fetch(`${baseUrl}/git/refs/heads/main`, {
      method: 'PATCH',
      headers,
      body: JSON.stringify({ sha: commit.sha, force: true }),
    })
    if (!patchRes.ok) {
      const err = await patchRes.json()
      return NextResponse.json({ error: `Ref update failed: ${err.message}` }, { status: 500 })
    }
  }

  // 6. Set default branch to main
  await fetch(`${baseUrl}`, {
    method: 'PATCH',
    headers,
    body: JSON.stringify({ default_branch: 'main' }),
  })

  const repoUrl = `https://github.com/${githubUsername}/${repoName}`
  const vercelDeployUrl = `https://vercel.com/new/clone?repository-url=${encodeURIComponent(`https://github.com/${githubUsername}/${repoName}`)}&project-name=${repoName}`

  return NextResponse.json({
    repoUrl,
    repoName,
    commitSha: commit.sha.slice(0, 7),
    filesCommitted: blobs.length,
    vercelDeployUrl,
  })
}
