import { NextRequest, NextResponse } from 'next/server'

export const runtime = 'nodejs'
export const maxDuration = 60

interface FileEntry {
  path: string
  content: string
}

interface CommitPayload {
  productName: string
  productSlug: string
  description: string
  files: FileEntry[]
  githubUsername: string
  githubToken: string
}

export async function POST(req: NextRequest) {
  const { productName, productSlug, description, files, githubUsername, githubToken } =
    await req.json() as CommitPayload

  const headers = {
    'Authorization': `Bearer ${githubToken}`,
    'Accept': 'application/vnd.github.v3+json',
    'Content-Type': 'application/json',
    'X-GitHub-Api-Version': '2022-11-28',
  }

  const repoName = productSlug.toLowerCase().replace(/[^a-z0-9-]/g, '-')

  // 1. Create the repository
  const createRepoRes = await fetch('https://api.github.com/user/repos', {
    method: 'POST',
    headers,
    body: JSON.stringify({
      name: repoName,
      description,
      private: false,
      auto_init: false,
    }),
  })

  if (!createRepoRes.ok) {
    const err = await createRepoRes.json()
    // If repo already exists, continue
    if (err.errors?.[0]?.message !== 'name already exists on this account') {
      return NextResponse.json({ error: err.message || 'Failed to create repo' }, { status: 400 })
    }
  }

  const repoData = await createRepoRes.json().catch(() => ({}))
  const repoUrl = repoData.html_url || `https://github.com/${githubUsername}/${repoName}`

  // 2. Commit all files via the Trees API (single commit, all files at once)
  const baseUrl = `https://api.github.com/repos/${githubUsername}/${repoName}`

  // Create blobs for each file
  const blobs: Array<{ path: string; mode: string; type: string; sha: string }> = []

  for (const file of files) {
    const blobRes = await fetch(`${baseUrl}/git/blobs`, {
      method: 'POST',
      headers,
      body: JSON.stringify({
        content: Buffer.from(file.content).toString('base64'),
        encoding: 'base64',
      }),
    })

    if (!blobRes.ok) continue

    const blob = await blobRes.json()
    blobs.push({
      path: file.path,
      mode: '100644',
      type: 'blob',
      sha: blob.sha,
    })
  }

  // Create tree
  const treeRes = await fetch(`${baseUrl}/git/trees`, {
    method: 'POST',
    headers,
    body: JSON.stringify({ tree: blobs }),
  })

  if (!treeRes.ok) {
    const err = await treeRes.json()
    return NextResponse.json({ error: err.message || 'Failed to create tree' }, { status: 400 })
  }

  const tree = await treeRes.json()

  // Create commit
  const commitRes = await fetch(`${baseUrl}/git/commits`, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      message: `feat: initial scaffold for ${productName}\n\nGenerated by AgentCo Platform\n7 AI divisions · real Claude API calls`,
      tree: tree.sha,
      parents: [],
    }),
  })

  if (!commitRes.ok) {
    const err = await commitRes.json()
    return NextResponse.json({ error: err.message || 'Failed to create commit' }, { status: 400 })
  }

  const commit = await commitRes.json()

  // Create main branch reference
  const refRes = await fetch(`${baseUrl}/git/refs`, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      ref: 'refs/heads/main',
      sha: commit.sha,
    }),
  })

  // If ref already exists, update it
  if (!refRes.ok) {
    await fetch(`${baseUrl}/git/refs/heads/main`, {
      method: 'PATCH',
      headers,
      body: JSON.stringify({ sha: commit.sha, force: true }),
    })
  }

  const vercelDeployUrl = `https://vercel.com/new/clone?repository-url=https://github.com/${githubUsername}/${repoName}`

  return NextResponse.json({
    repoUrl,
    repoName,
    commitSha: commit.sha,
    filesCommitted: blobs.length,
    vercelDeployUrl,
  })
}
